# Generated by Django 5.0.1 on 2024-01-24 18:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Primary_contact', models.CharField(max_length=13)),
                ('Secondary_contact', models.CharField(max_length=13)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Current_CTC', models.CharField(max_length=50)),
                ('Expected_CTC', models.CharField(max_length=50)),
                ('Notice_Period', models.CharField(max_length=50)),
                ('Current_designation', models.CharField(default=' ', max_length=100)),
                ('Applied_designation', models.CharField(default=' ', max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('General_Skills', models.TextField()),
                ('Technical_Skills', models.TextField()),
                ('Soft_Skills', models.TextField()),
                ('Job_portal_source', models.CharField(max_length=100)),
                ('Contacted_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 24, 23, 40, 9, 784102))),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moral_character', models.IntegerField(help_text=' Moral Character out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('punctuality', models.IntegerField(help_text=' Punctuality out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('health', models.IntegerField(help_text=' Health out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('poilitness_quiteness', models.IntegerField(help_text=' Poilitness and Quiteness out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('attitude', models.IntegerField(help_text=' marks out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('Career_goals', models.CharField(max_length=100)),
                ('understanding_level', models.IntegerField(help_text=' Understanding level out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('possitive_attitude', models.IntegerField(help_text=' Possitive attitude out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('exicutive', models.IntegerField(help_text=' Exicutive out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('responsibility', models.IntegerField(help_text=' Responsibility out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('response_ability', models.IntegerField(help_text=' Response Ability out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('team_handling', models.IntegerField(help_text=' Team handling out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('planing', models.IntegerField(help_text=' Planing out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('communicate_ability', models.IntegerField(help_text=' Communicate Ability out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('passion', models.CharField(max_length=100)),
                ('confidence', models.IntegerField(help_text=' Confidence out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('positive_mind', models.IntegerField(help_text=' Positive mind out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('profissional_background', models.CharField(max_length=100)),
                ('work_experience', models.IntegerField(help_text=' Work Experience Max 25 Years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('knowledge_level', models.IntegerField(help_text=' Knowledge Level out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('english_skils', models.IntegerField(help_text='English Skils out of 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('other_languages', models.IntegerField(help_text='Other Languages out of 15', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('consider_to_client', models.BooleanField(default=False)),
                ('Internal_hiring', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 24, 23, 40, 9, 784102))),
                ('remarks', models.TextField(default='Enter Remarks')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_app.registration')),
            ],
        ),
    ]
