# Generated by Django 5.0.1 on 2024-01-24 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 1, 11, 39, 647254)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 1, 11, 39, 647254)),
        ),
        migrations.AlterField(
            model_name='review',
            name='remarks',
            field=models.TextField(),
        ),
    ]
