# Generated by Django 5.0.1 on 2024-01-26 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 12, 6, 56, 275919)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 12, 6, 56, 275919)),
        ),
    ]
