# Generated by Django 5.0.1 on 2024-01-31 07:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_remove_review_exicutive_review_executive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='poilitness_quiteness',
        ),
        migrations.AddField(
            model_name='review',
            name='politeness_quiteness',
            field=models.FloatField(help_text=' Poilitness and Quiteness out of 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='Internal_hiring',
            field=models.CharField(choices=[(' ', ' '), ('yes', 'yes'), ('no', 'no')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='consider_to_client',
            field=models.CharField(choices=[(' ', ' '), ('yes', 'yes'), ('no', 'no')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 13, 3, 40, 209390)),
        ),
        migrations.AlterField(
            model_name='review',
            name='reject',
            field=models.CharField(choices=[(' ', ' '), ('yes', 'yes'), ('no', 'no')], default=' ', max_length=10),
        ),
    ]
