# Generated by Django 5.0.1 on 2024-01-31 09:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_remove_review_poilitness_quiteness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='politeness_quiteness',
            new_name='behaviour',
        ),
        migrations.RemoveField(
            model_name='review',
            name='positive_mind',
        ),
        migrations.RemoveField(
            model_name='review',
            name='possitive_attitude',
        ),
        migrations.AddField(
            model_name='review',
            name='possitive_attitude_and_mind',
            field=models.FloatField(help_text=' Possitive attitude out of 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 14, 53, 7, 116963)),
        ),
    ]
