# Generated by Django 5.0.1 on 2024-01-31 09:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_rename_politeness_quiteness_review_behaviour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Location',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='behaviour',
            field=models.FloatField(help_text=' Behaviour out of 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 15, 3, 51, 489434)),
        ),
        migrations.AlterField(
            model_name='review',
            name='possitive_attitude_and_mind',
            field=models.FloatField(help_text=' Possitive attitude and mind out of 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
