# Generated by Django 5.0.1 on 2024-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_alter_review_options_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(verbose_name='2024-01-31 18:10:25'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default='2024-01-31 18:10:25'),
        ),
    ]
