# Generated by Django 5.0.1 on 2024-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0014_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('certifications', models.FileField(upload_to='')),
                ('skills', models.CharField(max_length=100)),
                ('eperience', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
